### ISSUE TITLE
OSGi blog has broken social link images

### ISSUE THREAD

**Issue by bosschaert** [EclipseFdn/osgi.org#15]
If I go to https://blog.osgi.org/ I see that the images for the links to twitter, github etc in the top right corner are missing.

**Comment by autumnfound** [comment]
From what I can tell, that is managed outside of this repository on a wordpress/blogger site. Someone just created an issue about migrating that content over though! See #16

**Comment by bjhargrave** [comment]
I'll work on this.

@autumnfound  Since the blog is a Blogger site, we don't have a place for issues. So we decided to piggy back on this repo and use the `blog` label for them.
