### ISSUE TITLE
Migrate from blogger to hugo itself?

### ISSUE THREAD

**Issue by rotty3000** [EclipseFdn/osgi.org#16]
**Is your feature request related to a problem? Please describe.**
I wonder if it might not be worth the effort to just migrate the blog from blogger to hugo.

**Describe the solution you'd like**
Better integration...

**Describe alternatives you've considered**
There's a documented process.
https://gohugo.io/tools/migrations/#blogger

**Comment by bjhargrave** [comment]
@rotty3000, So you would propose migrating all the existing content to this Hugo site? What about all the blog.osgi.org URLs which are referenced? Or are you suggesting we make a new Hugo site for the blog with the old blogger content?

I am not sure this work is useful or a good use of our limited time.

**Comment by rotty3000** [comment]
so there's a tradeoff between keeping continuity between the two sites vs. migrating once and never having to worry about that again. Furthermore, it puts blogging in the same workflow as the site content itself which is more uniform and easier in my opinion.

**Comment by rotty3000** [comment]
My proposal is for sun-setting the blogger site entirely, and merging the exported content into a the hugo site.

**Comment by bjhargrave** [comment]
> My proposal is for sun-setting the blogger site entirely, and merging the exported content into a the hugo site.

This would then break all links to existing blog posts which I would not be in favor of.

**Comment by rotty3000** [comment]
I suppose that's a reasonable argument against. Thanks for the discussion.
