### ISSUE TITLE
Migrate website source repository to Eclipse Gitlab

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/osgi.org#41]
Over the last few months, we've been busy migrating some of our websites to Eclipse Gitlab:
https://gitlab.eclipse.org/eclipsefdn/it/websites

Today, I would like to recommend that we migrate this website repository under https://gitlab.eclipse.org/eclipsefdn/it/websites

This move makes it easier for foundation staff to collaborate and manage priorities since we can review issues by group https://gitlab.eclipse.org/groups/eclipsefdn/it/websites/-/issues

Triage is a bit more time-consuming on Github since we need to manually visit the issue queue of each project.

@EclipseFdn/osgi-org  Do you have any issues with us moving this repository? Also, if you agree, do you need some time to communicate this change with the WG before we do the move?

Thanks!

**Comment by bjhargrave** [comment]
Is the Eclipse GitLab functionally equivalent to GitHub? For example, what about GitHub Actions? This is nice to confirm PRs build property.

Is there an example of a WG's website which is already migrated to Eclipse GitLab?

From my point of view, I don't know GitLab. So such a move would be a negative for me. But I don't do the work on this repo, so I am sensitive to those that do. But this does seem counter to how many Eclipse projects are moving from Eclipse's old Git/Gerrit infra to GitHub and not Eclipse GitLab.

**Comment by chrisguindon** [comment]
@bjhargrave If you prefer GH, let me know and I will close this issue to WONTFIX.

**Comment by bjhargrave** [comment]
I do not want to stand in the way of reducing work for the EF team. But to migrate, we would need to replace the GitHub Actions workflows with equivalent Jenkins jobs. Would that be included in your migration plan? I sampled a couple of the issues linked above and both websites already have Jenkins job files.

**Comment by chrisguindon** [comment]
@bjhargrave If the GitHub actions are only needed to build the site to confirm that the code can compile, then yes, I can definitely create a Jenkins job for this project while doing this migration! It will be my pleasure!

**Comment by bjhargrave** [comment]
> If the GitHub actions are only needed to build the site to confirm that the code can compile

Yes, they just make sure the site builds to ensure bad PRs don't get merged.

If you are able to replace the GitHub Actions with a Jenkins job, then I am fine with migration. Thanks!

**Comment by chrisguindon** [comment]
The migrate to Gitlab is complete:
https://gitlab.eclipse.org/eclipsefdn/it/websites/osgi.org

You will notice that I updated the build status badge in the readme. It now points to our new Jenkins build Job:
https://foundation.eclipse.org/ci/webdev/job/public/job/osgi.org/job/main/

This new job is replacing the Github action! 

I will be closing this issue and arching this repo. I will make sure to include a note in the readme explaining that this repository has moved to Eclipse Gitlab: https://gitlab.eclipse.org/eclipsefdn/it/websites/osgi.org

I also made sure to give you write access to the new repo @bjhargrave !

Feel free to create an issue under https://gitlab.eclipse.org/eclipsefdn/it/websites/osgi.org/-/issues if you have any questions!
